download-external-modules: true
framework:
  - all
quiet: true
skip-check:
  - CKV_TF_1   # "Ensure Terraform module sources use a commit hash"
  - CKV_GIT_5  # "GitHub pull requests should require at least 2 approvals" only pipo
