---
# terraform-docs configuration
formatter: markdown table
version: ""
footer-from: "../../LICENSE.md"
recursive:
  enabled: false
sections:
  show:
    - inputs
    - providers
    - modules
    - outputs
    - footer

content: |-
  # How to use this module
  ```hcl
  # main.tf
  {{ include "main.tf" }}
  ```
  ```hcl
  # terraform.tfvars
  {{ include "terraform.tfvars" }}
  ```
  {{ include "../../docs/sops.md" }}
  {{ .Footer }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: false
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
