---
# .config/.terraform-docs.yml
formatter: markdown table  # this is required

version: ""

header-from: "docs/HEADER.md"
footer-from: "LICENSE.md"

recursive:
  enabled: false

sections:
  hide: []
  show: []

content: |-
  # Examples
  ## Complete
  ```hcl
  ## main.tf
  {{ include "examples/complete/main.tf" }}
  ## terraform.tfvars
  {{ include "examples/complete/terraform.tfvars" }}
  ```
  ## Resources
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}
  {{ .Header }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}


output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
