---
name: terratest

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  id-token: write  # This is required to use the AWS Credentials


jobs:
  terratest:
    uses: flufi-io/workflows/.github/workflows/terratest.yaml@main
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
