---
name: terratest

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  id-token: write  # This is required to use the AWS Credentials


jobs:
  terratest:
    uses: flufi-io/workflows/.github/workflows/terratest.yaml@terratest
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      working-directory: examples/complete
      env: |
        TF_VAR_github_token=${{ secrets.GH_TOKEN_PAT }}
